#! /bin/sh

#  ██
# ░██              ██████
# ░██       ██████░██░░░██ ███     ██ ██████████
# ░██████  ██░░░░ ░██  ░██░░██  █ ░██░░██░░██░░██
# ░██░░░██░░█████ ░██████  ░██ ███░██ ░██ ░██ ░██
# ░██  ░██ ░░░░░██░██░░░   ░████░████ ░██ ░██ ░██
# ░██████  ██████ ░██      ███░ ░░░██ ███ ░██ ░██
# ░░░░░   ░░░░░░  ░░      ░░░    ░░░ ░░░  ░░  ░░

#launch sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &
#config monitors
xrandr --output HDMI1 --primary --mode 1920x1080  &
#launch polybar
~/.config/polybar/launch.sh &
#picom
picom &
#swallowing
pgrep bspswallow || bspswallow &
#wallpaper and colorscheme
#feh --bg-fill ~/walls/gho.png &
#desktops
bspc monitor -d 1 2 3 4 5 6 7 8 9
#self explainatory
bspc config border_width         0
bspc config window_gap          16

#bspc config top_padding		30
bspc config bottom_padding	16
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color1    5"
bspc config presel_feedback_color "$color    1"
bspc config focus_follows_pointer true
#i dont know what this means lmao
bspc config focus_follows_pointer true
bspc rule -a Firefox desktop='II'
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=pc rule -a Pavucontrol state=floating rectangle 200x200+50+50 sticky=off 
#for my "thiccpad"
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Tapping Enabled" 1
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Natural Scrolling Enabled" 1


